name: SonarCloud Scan

on:
  pull_request:
    branches:
      - develop
    paths:
      - '**/*.java'

jobs:
  sonarcloud:
    name: SonarCloud Scan
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '17'

      - name: Cache Gradle dependencies
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*', '**/gradle-wrapper.properties') }}
          restore-keys: ${{ runner.os }}-gradle

      - name: Build with Gradle
        run: |
          cd classroom
          ./gradlew build

      - name: SonarCloud Scan
        run: |
          cd classroom
          sonar-scanner -Dsonar.projectKey=bhos-qa_lab-4-rgasimzade -Dsonar.organization=bhos-qa
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}